<link rel="stylesheet" href="<?= $this->baseUrl() ?>/css/uxmonespace.css" />
<link rel="stylesheet" href="<?= $this->baseUrl() ?>/css/uxcalendrier.css" />
<link rel="stylesheet" href="<?= $this->baseUrl() ?>/css/uxzf.css" />
<script src='https://cdn.jsdelivr.net/npm/fullcalendar@6.1.10/index.global.min.js'></script>
<script src='https://cdn.jsdelivr.net/npm/@fullcalendar/core@6.1.10/locales/fr.global.min.js'></script>
<script src="/jquery/ux/calendrier/monespace.js"></script>
<script src="/jquery/ux/calendrier/initgrid.js"></script>
<div id="calme"></div>
<div id="sources_calendrier">
    <i class="fa-solid fa-eye"></i>
    <span>
        <input type="checkbox" id="sourcedefault" value="default" checked="checked" />
        <label for="sourcedefault">Application</label>
    </span>
    <span class='<?= $this->sourceTODO ?>'>
        <input type="checkbox" id="sourcetodo" value="todo" checked="checked" />
        <label for="sourcetodo">TODO</label>
    </span>
    <?php foreach ($this->sources as $i => $source) { ?>
    <script>
    sources.push({
        id: '<?= $source['source'] ?>',
        url: '/uxmonespace/sourcecal',
        method: 'POST',
        startParam: 'debut',
        endParam: 'fin',
        extraParams: {
            url: '<?= $source['url'] ?>'
        },
        color: '<?= $source['couleur'] ?: '#ff8000' ?>',
        textColor: <?php
                            $hex = $source['couleur'] ?: '#ff8000';
                            $r = hexdec(substr($hex, 1, 2));
                            $g = hexdec(substr($hex, 3, 2));
                            $b = hexdec(substr($hex, 5, 2));
                            if ((0.299 * $r + 0.587 * $g + 0.114 * $b) / 255 > 0.5) echo "'#000000'";
                            else echo "'#ffffff'"; ?>
    })
    </script>
    <span>
        <input type="checkbox" id="source<?= $i ?>" value="<?= $source['source'] ?>" checked="checked" />
        <label for="source<?= $i ?>"><?= $source['titre'] ?></label>
    </span>
    <?php } ?>
    <?php if (NR_Utilitaires::verificationAbonnementModule('calendar_sync')) : ?>
    <button id="btnpublier" class="rz-bouton" type="button">Partager</button>
    <?php endif; ?>
</div>

<div class="modal fade" id="addEventModal" tabindex="-1">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Ajouter un événement</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
            </div>
            <div class="modal-body">
                <label for="event-title" class="form-label">Titre</label>
                <input type="text" id="event-title" class="form-control mb-2" placeholder="Nom de l'événement">

                <label for="event-date" class="form-label">Date</label>
                <input type="datetime-local" id="event-date" class="form-control mb-2">

                <button id="save-event" class="btn btn-success w-100">Enregistrer</button>
            </div>
        </div>
    </div>
</div>
</div>
<div id="filtres_calendrier" class="div-wrapper">
    <input id="rechcheckboxlist" type="text" placeholder="Rechercher">
    <span class="contact selecttout">
        <input type="checkbox" id="selecttoutcb">
        <label for="selecttoutcb">Sélectionner tout</label>
        <i class="fas fa-check"></i>
    </span>
</div>

<div class="cell div-wrapper Zfcaldavevent">
    <div id="cal-accordion" class="cal-menu-parent">
        <ul class="cal-menu">
            <li class="cal-menu-child active">
                <a href="#" class="cal-accordion-a d-flex align-items-center fs-4 py-2"><i
                        class="fas fa-quote-left fa-fw" aria-hidden="true"></i>Information <label
                        class="tab__label ps-1"></label></a>
                <div class="cal-menu-content">
                    <?php echo NR_Utilitaires::minifyHTML($this->partial(
                        "/uxmonespace/partialzfcaldavevent.phtml",
                        [
                            "vr" => 'calmemodif',
                            "nom_affiche" => '',
                            "obligatoire" => true,
                            "infobulle" => "Cliquez sur un évènement du calendrier pour en afficher les détails ici.",
                            "uid" => ''
                        ]
                    )); ?>
                    <span class="calmemodifbt">
                        <a id="calmemodiflink" target="_blank">Lien vers la fiche</a>
                        <button class="rz-bouton" onclick="saveZfcaldavevent('calmemodif')" title="Enregistrer"
                            disabled>Enregistrer les modifications</button>
                    </span>
                </div>
            </li>
            <li class="cal-menu-child">
                <a href="#" class="cal-accordion-a d-flex align-items-center fs-4 py-2"><i
                        class="fas fa-cog fa-fw"></i>Ajouter une nouvelle fiche évènement <label
                        class="tab__label ps-1"></label></a>
                <div id="calmeajout" class="cal-menu-content">
                    <div class="corpspopup">
                        <fieldset id="ajout_fiche">
                            <span>
                                <label for="selectajout">Sélectionner un type de fiche : </label>
                                <select id="selectajout" class="champmodif">
                                    <option></option>
                                    <?php foreach ($this->listeTypefiche as $tf) : ?>
                                    <option data-typek="<?= $tf['typeK'] ?>" data-tkna="<?= $tf['tkna'] ?>"
                                        data-vr="<?= $tf['vr'] ?>" value="<?= $tf['typefiche'] ?>">
                                        <?= $tf['nom_affiche'] ?> (<?= $tf['tkna'] ?>)
                                    </option>
                                    <?php endforeach; ?>
                                </select>
                            </span>
                            <span id="selectk">
                                <span>
                                    <label for="choixk"></label>
                                    <input id="rechchoixk" type="text" class="inputtableur"
                                        placeholder="Chercher dans la liste" />
                                </span>
                                <select id="choixk" class="champmodif" required></select>
                            </span>
                        </fieldset>
                        <?php echo NR_Utilitaires::minifyHTML($this->partial(
                            "/uxmonespace/partialzfcaldavevent.phtml",
                            [
                                "vr" => 'ajout_evenement',
                                "nom_affiche" => '',
                                "obligatoire" => true,
                                "uid" => ''
                            ]
                        )); ?>
                    </div>
                    <div class="btspopup">
                        <button id="newevent" class="rz-bouton" type="button">Enregistrer la saisie</button>
                    </div>
                </div>
            </li>
            <?php if (NR_Utilitaires::verificationAbonnementModule('calendar_sync')) : ?>
            <li class="cal-menu-child">
                <a href="#" class="cal-accordion-a d-flex align-items-center fs-4 py-2"><i class="fas fa-pencil fa-fw"
                        aria-hidden="true"></i>Gérer les calendriers <label class="tab__label ps-1"></label></a>
                <div id="gestion_sources" class="cal-menu-content">
                    <div class="corpspopup">
                        <?php foreach ($this->sources as $i => $source) : ?>
                        <span data_sourceId="<?= $source['source'] ?>">
                            <input type="text" name="titre" value="<?= $source['titre'] ?>"
                                placeholder="Nom du calendrier" required />
                            <span class="rz-infobulle-declencheur source_url">&#9432;
                                <div class="rz-infobulle-texte">
                                    <?= $source['url'] ?>
                                </div>
                            </span>
                            <input class="rz-bouton" type="color" name="couleur" value="<?= $source['couleur'] ?>" />
                            <input class="rz-bouton" type="button" value="Modifier" onclick="modsrcevent(this)" />
                            <input class="rz-bouton" type="button" value="Supprimer" onclick="delsrcevent(this)" />
                        </span>
                        <?php endforeach; ?>
                        <fieldset id="newsrc">
                            <legend>Ajouter un calendrier</legend>
                            <input type="url" name="url" class="inputtableur" placeholder="URL du calendrier"
                                required />
                            <input type="text" name="titre" class="inputtableur" placeholder="Nom du calendrier"
                                required />
                            <input class="rz-bouton" type="color" name="couleur" value="#ff8000" />
                            <input class="rz-bouton" type="button" value="Ajouter" onclick="addsrcevent()" />
                        </fieldset>
                    </div>
                    <div class="btspopup">
                    </div>
                </div>
            </li>
            <?php endif; ?>
        </ul>
    </div>
</div>
<div id="lienprive" class="cal-popup-publier">
    <div class="cal-popup-inner">
        <div class="cal-popup-inner-content">
            <h1>Partager le calendrier <?= NR_Utilitaires::getTitreApplication(true) ?></h1>
            <script>
            function toClipboard() {
                if (!navigator.clipboard) return;
                const lien = document.querySelector('[name="lienprive"]')
                navigator.clipboard.writeText(lien.value).then(() => {
                    alert("Lien copié dans le presse-papier")
                })
            }
            </script>
            <input type="text" readonly name="lienprive" value="<?= $this->lienprive ?>" />
            <input class="rz-bouton" type="button" value="Copier dans le presse-papier" onclick="toClipboard()" />
            <input class="rz-bouton" type="button" value="Reinitialiser le lien" onclick="reinitlink()" />
        </div>
        <span class="cal-popup-close fermerpopup">X</span>
    </div>
</div>